### ISSUE TITLE
Is supporting Numpy docstring possible?

### ISSUE THREAD

**Issue by hcoohb** [daizutabi/mkapi#1]
Hi,

I really like this project and how the documentation is rendered.
Is there any plan to extend this plugin to support the Numpy Doctring, as this is very commonly used?

Thanks and regards,

**Comment by daizutabi** [comment]
Thank you for your interesting.

Although I chose the Google style because I prefer it to the Numpy style, I agree that an Python API generator should support both styles. I'm planning to write a new parser for them, but I'm not sure when it will be released.

**Comment by daizutabi** [comment]
Now MkApi supports both Google and NumPy styles.

**Comment by hcoohb** [comment]
Wow, that was impressively quick !!!

I had some errors while using the pypi version (I'll raise another separate issue), but after fixing it, from my first trials, that looks great!!

Amazing, thanks a lot for this fast addition!
