### ISSUE TITLE
Pypi package does not include `templates` and `theme` folders

### ISSUE THREAD

**Issue by hcoohb** [daizutabi/mkapi#2]
Hi,

It seems that the package distributed through pypi does not include `templates` folder which produces an error in mkdocs:
```
(.venv) mkdocs serve
INFO    -  Building documentation...

[WinError 3] The system cannot find the path specified: 'c:\\users\\my.user\\devel\\rics\\pi_lib\\.venv\\lib\\site-packages\\mkapi\\templates'
```
I installed it via `pip install mkapi` (version 0.4.0)

Placing the templates folder in the module path works like a charm.
Also, not sure if needed but the `theme` folder isn't distributed either.

**Comment by daizutabi** [comment]
Thank you for your information. `setup.py` was wrong. I fixed it. Please update Version 0.4.2 or later.

**Comment by hcoohb** [comment]
Awesome,
works great now.
Thanks
