### ISSUE TITLE
pip install mkapi not working

### ISSUE THREAD

**Issue by CarlosVaquero** [daizutabi/mkapi#21]
When running  pip install mkapi: 

Could not find a version that satisfies the requirement mkapi (from versions: )
No matching distribution found for mkapi

**Comment by daizutabi** [comment]
Could you show the log of pip command?

**Comment by timvink** [comment]
@CarlosVaquero I got the same message. Probably you are running a python version lower than 3.7 (see your version with `python -V`), while `mkapi` supports python 3.7+
