### ISSUE TITLE
Support python 3.5+

### ISSUE THREAD

**Issue by timvink** [daizutabi/mkapi#28]
Hi @daizutabi ,

Is there any reason this package is does not support python 3.5 and 3.6? MkDocs officially still supports 3.5+ ([link](https://github.com/mkdocs/mkdocs/blob/ff0b7260564e65b6547fd41753ec971e4237823b/setup.py#L87)). My companies hadoop cluster is still running python 3.6, and I'd like to use your package there.

Any chance you'd be willing to increase support for older python versions?

**Comment by daizutabi** [comment]
Thank you for your interest. MkApi uses [`dataclass`](https://docs.python.org/3/library/dataclasses.html) that was introduced in version 3.7. I think you can use a virtual environment of Python 3.7 to create the documentation.

**Comment by timvink** [comment]
Yeah really cool package, well done!

Of course there are always ways around, like virtualenv or building the docs locally, but I wanted to see if there was a quick win to make it easier to use for colleagues.

I had a quick try using the backported [dataclass](https://pypi.org/project/dataclasses/) package to support python 3.6 but pytest failed.

```
            elif k == 2:
                assert not markdown
            elif k == 3:
                x = signature.to_string(type)
>               assert x == "(list of int, dict(str: list of float))"
E               AssertionError: assert '[Tuple](!typing.Tuple)' == '(list of int...st of float))'
E                 - (list of int, dict(str: list of float))
E                 + [Tuple](!typing.Tuple)

tests/core/test_core_attribute.py:40: AssertionError

---------- coverage: platform darwin, python 3.6.10-final-0 ----------
Coverage HTML written to dir htmlcov

========================================================== short test summary info ==========================================================
FAILED tests/core/test_core_attribute.py::test_class_attribute - AssertionError: assert '[Tuple](!typing.Tuple)' == '(list of int...st of ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 failed, 2 passed in 1.27s ========================================================
```

So no quick win :) Let's stay in the future then, feel free to close!
