### ISSUE TITLE
Consider a conda package

### ISSUE THREAD

**Issue by andrew-schweitzer-analog** [daizutabi/mkapi#29]
It would help teams using conda to use this library if there were a conda package on conda-forge. You can pip-install into a conda environment, but that is problematic because you will get dependencies from unpredictable locations, depending on what is already installed in the environment. I have not myself tried [these](https://conda-forge.org/#add_recipe) instructions, so I don't know how much work this is. 

Thanks

Andy

**Comment by daizutabi** [comment]
Mkapi has been added to the conda-forge by [this PR](https://github.com/conda-forge/staged-recipes/pull/13002).

Now you can install the package via `conda install -c conda-forge mkapi`.
