### ISSUE TITLE
[Enhancement] Add Node header into the table of content?

### ISSUE THREAD

**Issue by hcoohb** [daizutabi/mkapi#3]
Hi,

First, thanks for allowing me to make beautiful API docs so easily!!

This is more a feature suggestion and I am not sure of the internal, so I don't know if it is possible.
But could we have the option to add the main nodes to the toc?
So If I use `![mkapi](package.module.Class)`, then that would also add the Class methods in the toc ?

That would be terrific

**Comment by daizutabi** [comment]
I'm not sure but if my understanding is correct, MkDocs builds the toc from Markdown's header statement (#, ##, ###, etc.). On the other hand,  MkApi uses nested `div` tags to represent tree structure of `Node`. I think adding header is potentially possible but some survey is needed to understand how MkDocs builds the toc.

**Comment by daizutabi** [comment]
I think this is not the exact feature you hope, but now MkApi creates Classes, Functions, and Methods sections at module and class levels. These sections work as a kind of toc.

<img width="455" alt="img" src="https://user-images.githubusercontent.com/17495937/84401008-b8b3e000-ac3d-11ea-8a3e-126e204d9fb1.png">

**Comment by daizutabi** [comment]
In Version 0.8.4, if you use page mode, MkApi creates toc in nav.

<img width="230" alt="img2" src="https://user-images.githubusercontent.com/17495937/84488720-907abe80-acdb-11ea-824e-566e8ac3fb44.png">

(Readthedocs theme)

**Comment by daizutabi** [comment]
You can also use "[Heading mode](https://mkapi.daizutabi.net/examples/google_style/#heading-mode)" to create toc for non page mode.

```markdown
## ![mkapi](pi_lib.Connection)
```

I found a bug in the heading mode and fixed it in Version 1.0.10, so please update the package to use the method above.
