### ISSUE TITLE
[Enhancement] hide __init__() method if no docstring

### ISSUE THREAD

**Issue by hcoohb** [daizutabi/mkapi#4]
Another possible enhancement could be to hide the __init__() method when displaying a class if the docstring is empty, since all parameters appear in the class header and the docstring of the class supposedly document those.

Currently a section with the __init__ method is created with the following content :
`Initialize self. See help(type(self)) for accurate signature.`
even if there is no docstring

**Comment by daizutabi** [comment]
I fixed the problem. Please use Version 0.5.1 or later.
Current behavior: If there is a class header docstring, an **init()** docstring is ignored regardless of its contents. If there is not a class header docstring AND an **init()** docstring does not start with `Initialize self`, the **init()** docstring is transfered to the class header docstring.

**Comment by hcoohb** [comment]
Perfect, thanks for the quick resolution again!
