### ISSUE TITLE
Override package/module discovery in page mode to load file even if no docstring is present

### ISSUE THREAD

**Issue by JosXa** [daizutabi/mkapi#42]
In the docs, it says:

![image](https://user-images.githubusercontent.com/7313176/97115156-66a7be80-16f5-11eb-804e-449b61479c16.png)

For Python files that contain only a single class however, adding a docstring feels kind of unnecessary and redundant. Is it possible to override this functionality and force loading files even if they have no docstring? My current workaround is to add a docstring with invisible character, which kinda works but creates too much blank space in the docs:

![image](https://user-images.githubusercontent.com/7313176/97115210-ca31ec00-16f5-11eb-8bc4-430c2abfe758.png)

**Comment by daizutabi** [comment]
In Version 1.0.14, MkApi processes packages/modules if their members (class/function) have docstring.
