### ISSUE TITLE
[Enhancement] Document only a specifc method from a class

### ISSUE THREAD

**Issue by hcoohb** [daizutabi/mkapi#5]
Another use case that I could see myself using is if we only want to display the bloc regarding a specific method from a class. So for example using: `![mkapi](numpy_style.ExampleClass.message)`

It seems at the moment it is not possible, or at least it created an error on my machine.
And not sure if there is another way to achieve this, but that would be interesting to have the possibility to do so.

Thanks!

**Comment by daizutabi** [comment]
Good point. Thanks to your indication, I found several bugs in my code. Now you can use `![mkapi](numpy_style.ExampleClass.message)` in version 0.5.2 or later.

I updated [the documentation](https://mkapi.daizutabi.net/numpy_style/#method).

**Comment by hcoohb** [comment]
Thanks for fixing this issue!
