### ISSUE TITLE
Official answer - Is this project still maintained?

### ISSUE THREAD

**Issue by janaka** [daizutabi/mkapi#59]
Hi @daizutabi, would appreciate if you could declare the official position of this project. Seems like it's no longer being actively developed or maintain. This is a shame but fair enough. Can you confirm pls?

fwiw our main blocker is it seems to not work with newer versions of Python (3.11 in our case but seem to be broken from Python v3.9 onwards based on other users comments). #56 

Thanks

**Comment by daizutabi** [comment]
@janaka, I recently restarted development on this project. Our top priority is support for Python 3.8 to 3.12.

**Comment by daizutabi** [comment]
@janaka, MkAPI v2 has been released.
