### ISSUE TITLE
IPython dependency problem

### ISSUE THREAD

**Issue by Ahrak** [daizutabi/mkapi#6]
Hello,

first of all i like your project. Its currently the best option for creating api-docs with mkdocs using google-style, nice work :wink:  

Current Release 0.6.1 depends on Ipython package which is not listed in the dependencies.
after i updated the library and build with mkdocs i get the following error:
```
$mkdocs build -c -v
...
.env/lib/python3.8/site-packages/mkapi/utils.py", line 1, in <module>
    from IPython.display import HTML
ModuleNotFoundError: No module named 'IPython'
```

**Comment by daizutabi** [comment]
Thank you for your comment and reporting the issue.

`from IPython ...` has been moved inside a local function to prevent the exception.

Please update Vertion 0.6.2 or later.
