### ISSUE TITLE
Support python 3.11

### ISSUE THREAD

**Issue by frazane** [daizutabi/mkapi#93]
Hi there, thanks for publishing this library! I'd like to use it for [scoringrules](https://github.com/frazane/scoringrules). I am wondering, would it be possible to add support for python 3.11 (or even 3.10)? I cannot install it because my package supports `>=3.10, <=3.12` and I guess the same applies to many other projects that follow numpy's version support policy (see https://numpy.org/neps/nep-0029-deprecation_policy.html).

**Comment by daizutabi** [comment]
@frazane Thank you for your suggestion. Now, MkAPI v2.1.0 supports Python >= 3.10.
